name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JMeter
      run: sudo apt-get install -y jmeter

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Populate database with test data
      run: python insert_data.py

    - name: Start Flask API
      run: |
        nohup python app.py &
        sleep 5

    - name: Run Performance Test
      run: ./run_performance_test.sh

